-- ========================================================
-- Cloud-Diary Supabase Database Schema & RLS Policies
-- ========================================================

-- 1. Create Events Table
CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  start TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security on Events
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- Events RLS Policies (Per-User Isolation)
CREATE POLICY "Users can select own events" ON public.events
  FOR SELECT USING (auth.uid() = owner);

CREATE POLICY "Users can insert own events" ON public.events
  FOR INSERT WITH CHECK (auth.uid() = owner);

CREATE POLICY "Users can update own events" ON public.events
  FOR UPDATE USING (auth.uid() = owner) WITH CHECK (auth.uid() = owner);

CREATE POLICY "Users can delete own events" ON public.events
  FOR DELETE USING (auth.uid() = owner);


-- 2. Create Notes Table
CREATE TABLE IF NOT EXISTS public.notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security on Notes
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;

-- Notes RLS Policies (Per-User Isolation)
CREATE POLICY "Users can select own notes" ON public.notes
  FOR SELECT USING (auth.uid() = owner);

CREATE POLICY "Users can insert own notes" ON public.notes
  FOR INSERT WITH CHECK (auth.uid() = owner);

CREATE POLICY "Users can update own notes" ON public.notes
  FOR UPDATE USING (auth.uid() = owner) WITH CHECK (auth.uid() = owner);

CREATE POLICY "Users can delete own notes" ON public.notes
  FOR DELETE USING (auth.uid() = owner);


-- 3. Database Triggers to automatically set owner = auth.uid()
CREATE OR REPLACE FUNCTION public.set_owner_on_insert()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.owner IS NULL OR NEW.owner != auth.uid() THEN
    NEW.owner := auth.uid();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for events table
DROP TRIGGER IF EXISTS tr_set_events_owner ON public.events;
CREATE TRIGGER tr_set_events_owner
  BEFORE INSERT ON public.events
  FOR EACH ROW
  EXECUTE FUNCTION public.set_owner_on_insert();

-- Trigger for notes table
DROP TRIGGER IF EXISTS tr_set_notes_owner ON public.notes;
CREATE TRIGGER tr_set_notes_owner
  BEFORE INSERT ON public.notes
  FOR EACH ROW
  EXECUTE FUNCTION public.set_owner_on_insert();


-- 4. Indexes for fast query performance by owner
CREATE INDEX IF NOT EXISTS events_owner_idx ON public.events(owner);
CREATE INDEX IF NOT EXISTS notes_owner_idx ON public.notes(owner);
